#!/usr/bin/env bash
ENV_VAR_PREFIX="ANDROID_NETWORK_TOOLS"

APP_NAME="Android Network Tools Sample App"

# Slack webhook settings
SLACK_CHANNEL="#mat-testing"
SLACK_WEBHOOK_URL="https://hooks.slack.com/services/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"
ICON_URL="https://github.com/stealthcopter/AndroidNetworkTools/raw/master/app/src/main/res/mipmap-xhdpi/ic_launcher.png"

# Settings for github releases
GITHUB_RELEASE_MODULE="library"
GITHUB_RELEASE_DESC="This release was automatically generated by the CI server"
GITHUB_RELEASE_URL="https://api.github.com/repos/stealthcopter/AndroidNetworkTools/releases"
GITHUB_RELEASE_TOKEN=$ANDROID_NETWORK_TOOLS_GITHUB_RELEASE_TOKEN

# Fires a webhook to slack to notify of successful upload to beta
function webhook {

    gradle_app_name="$1"
    message="$2"
    git_hash=`git rev-parse --short HEAD`
    version=`cat ${gradle_app_name}/build.gradle | grep -m 1 versionName | cut -d'"' -f 2`
    
    # TESTING WEBHOOK https://hooks.slack.com/services/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
    
    echo $message
    echo $channel $gradle_app_name $APP_NAME $version $ICON_URL

    curl -X POST --data-urlencode 'payload={"channel": "'"$SLACK_CHANNEL"'", "username": "CirclCI Deployment Bot", "text": "*'"$APP_NAME"'* version *'"$version"'*  <'"https://github.com/scottyab/rootbeer/commits/$git_hash"'|'"$git_hash"'> '"$message"'", "icon_url": "'"$ICON_URL"'"}' $SLACK_WEBHOOK_URL

}  